{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMFkq0EAuy99DE2K0saKX8V",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/charan3949/deep-learning/blob/main/lab4_rnn.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wiMdP0AOZQKd",
        "outputId": "91c40522-be83-4fd4-901e-888e7fa23ffb"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Using device: cpu\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "100%|██████████| 9.91M/9.91M [00:00<00:00, 41.2MB/s]\n",
            "100%|██████████| 28.9k/28.9k [00:00<00:00, 1.11MB/s]\n",
            "100%|██████████| 1.65M/1.65M [00:00<00:00, 9.94MB/s]\n",
            "100%|██████████| 4.54k/4.54k [00:00<00:00, 10.2MB/s]\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Train samples: 2000, Test samples: 500\n",
            "\n",
            "=========================\n",
            "Running GRU Experiments\n",
            "=========================\n",
            "\n",
            "======================================\n",
            "Starting GRU Trial 0\n",
            "======================================\n",
            "GRU Trial 0 | Epoch 1/3 | Train Acc: 0.1580, Test Acc: 0.1020\n",
            "GRU Trial 0 | Epoch 2/3 | Train Acc: 0.1490, Test Acc: 0.2080\n",
            "GRU Trial 0 | Epoch 3/3 | Train Acc: 0.2480, Test Acc: 0.2380\n",
            "\n",
            "======================================\n",
            "Starting GRU Trial 1\n",
            "======================================\n",
            "GRU Trial 1 | Epoch 1/3 | Train Acc: 0.1190, Test Acc: 0.1020\n",
            "GRU Trial 1 | Epoch 2/3 | Train Acc: 0.1320, Test Acc: 0.1420\n",
            "GRU Trial 1 | Epoch 3/3 | Train Acc: 0.2015, Test Acc: 0.2540\n",
            "\n",
            "======================================\n",
            "Starting GRU Trial 2\n",
            "======================================\n",
            "GRU Trial 2 | Epoch 1/3 | Train Acc: 0.1255, Test Acc: 0.1020\n",
            "GRU Trial 2 | Epoch 2/3 | Train Acc: 0.1500, Test Acc: 0.1620\n",
            "GRU Trial 2 | Epoch 3/3 | Train Acc: 0.2265, Test Acc: 0.2900\n",
            "\n",
            "GRU final test accuracies: [0.238 0.254 0.29 ]\n",
            "GRU mean test accuracy: 0.2607\n",
            "GRU mean classification error: 0.7393\n",
            "\n",
            "\n",
            "=========================\n",
            "Running MGU Experiments\n",
            "=========================\n",
            "\n",
            "======================================\n",
            "Starting MGU Trial 0\n",
            "======================================\n",
            "MGU Trial 0 | Epoch 1/3 | Train Acc: 0.1220, Test Acc: 0.1020\n",
            "MGU Trial 0 | Epoch 2/3 | Train Acc: 0.1615, Test Acc: 0.2180\n",
            "MGU Trial 0 | Epoch 3/3 | Train Acc: 0.2665, Test Acc: 0.2100\n",
            "\n",
            "======================================\n",
            "Starting MGU Trial 1\n",
            "======================================\n",
            "MGU Trial 1 | Epoch 1/3 | Train Acc: 0.1135, Test Acc: 0.1020\n",
            "MGU Trial 1 | Epoch 2/3 | Train Acc: 0.1670, Test Acc: 0.1300\n",
            "MGU Trial 1 | Epoch 3/3 | Train Acc: 0.1930, Test Acc: 0.1460\n",
            "\n",
            "======================================\n",
            "Starting MGU Trial 2\n",
            "======================================\n",
            "MGU Trial 2 | Epoch 1/3 | Train Acc: 0.1295, Test Acc: 0.1680\n",
            "MGU Trial 2 | Epoch 2/3 | Train Acc: 0.1455, Test Acc: 0.1580\n",
            "MGU Trial 2 | Epoch 3/3 | Train Acc: 0.1580, Test Acc: 0.1880\n",
            "\n",
            "MGU final test accuracies: [0.21  0.146 0.188]\n",
            "MGU mean test accuracy: 0.1813\n",
            "MGU mean classification error: 0.8187\n",
            "\n",
            "DONE. Plots saved as:\n",
            "  gru_trial0.png, gru_trial1.png, gru_trial2.png\n",
            "  mgu_trial0.png, mgu_trial1.png, mgu_trial2.png\n"
          ]
        }
      ],
      "source": [
        "# ============================================================\n",
        "# CS 599 – Foundations of Deep Learning\n",
        "# Assignment #00100 – Problem 1\n",
        "#\n",
        "# Student: Sai Charan Kalagoni (sk3949@nau.edu)\n",
        "#\n",
        "# Implements:\n",
        "#   * Custom GRU and MGU cells using basic PyTorch ops\n",
        "#   * Shallow RNN classifier that treats each image row as a time step\n",
        "#   * 3 trials for GRU and 3 trials for MGU\n",
        "#   * Training vs test accuracy plots for each trial (6 PNGs)\n",
        "#   * Final test accuracies and mean classification errors\n",
        "# ============================================================\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import DataLoader, Subset\n",
        "import torchvision\n",
        "import torchvision.transforms as transforms\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "\n",
        "# ---------------------------\n",
        "# Config (tuned to be fast)\n",
        "# ---------------------------\n",
        "INPUT_DIM = 28          # each time step is one row of 28 pixels\n",
        "HIDDEN_DIM = 64         # hidden size of GRU/MGU\n",
        "NUM_CLASSES = 10        # MNIST digits 0–9\n",
        "BATCH_SIZE = 128\n",
        "EPOCHS = 3              # epochs per trial\n",
        "TRIALS = 3              # number of trials for each model\n",
        "\n",
        "MAX_TRAIN_SAMPLES = 2000   # subset size to make it fast\n",
        "MAX_TEST_SAMPLES  = 500\n",
        "\n",
        "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "print(\"Using device:\", DEVICE)\n",
        "\n",
        "torch.set_num_threads(2)\n",
        "torch.manual_seed(0)\n",
        "np.random.seed(0)\n",
        "\n",
        "# ============================================================\n",
        "# Custom GRU cell (from assignment equations)\n",
        "# ============================================================\n",
        "class GRUCellCustom(nn.Module):\n",
        "    \"\"\"\n",
        "    Gated Recurrent Unit (GRU) cell:\n",
        "\n",
        "        z_t = σ(W_z [h_{t-1}, x_t] + b_z)\n",
        "        r_t = σ(W_r [h_{t-1}, x_t] + b_r)\n",
        "        h~_t = tanh(W_s [r_t ⊙ h_{t-1}, x_t] + b_s)\n",
        "        h_t = (1 - z_t) ⊙ h_{t-1} + z_t ⊙ h~_t\n",
        "    \"\"\"\n",
        "    def __init__(self, inp_dim, hid_dim):\n",
        "        super().__init__()\n",
        "        self.hid_dim = hid_dim\n",
        "        self.z = nn.Linear(inp_dim + hid_dim, hid_dim)\n",
        "        self.r = nn.Linear(inp_dim + hid_dim, hid_dim)\n",
        "        self.h = nn.Linear(inp_dim + hid_dim, hid_dim)\n",
        "\n",
        "    def forward(self, x_t, h_prev):\n",
        "        # x_t: (batch, inp_dim), h_prev: (batch, hid_dim)\n",
        "        concat = torch.cat([h_prev, x_t], dim=1)\n",
        "        z_t = torch.sigmoid(self.z(concat))\n",
        "        r_t = torch.sigmoid(self.r(concat))\n",
        "\n",
        "        concat_reset = torch.cat([r_t * h_prev, x_t], dim=1)\n",
        "        h_tilde = torch.tanh(self.h(concat_reset))\n",
        "\n",
        "        h_new = (1.0 - z_t) * h_prev + z_t * h_tilde\n",
        "        return h_new\n",
        "\n",
        "# ============================================================\n",
        "# Custom MGU cell (from assignment equations)\n",
        "# ============================================================\n",
        "class MGUCellCustom(nn.Module):\n",
        "    \"\"\"\n",
        "    Minimal Gated Unit (MGU) cell:\n",
        "\n",
        "        f_t = σ(W_f [h_{t-1}, x_t] + b_f)\n",
        "        h~_t = tanh(W_s [f_t ⊙ h_{t-1}, x_t] + b_s)\n",
        "        h_t = (1 - f_t) ⊙ h_{t-1} + f_t ⊙ h~_t\n",
        "    \"\"\"\n",
        "    def __init__(self, inp_dim, hid_dim):\n",
        "        super().__init__()\n",
        "        self.hid_dim = hid_dim\n",
        "        self.f = nn.Linear(inp_dim + hid_dim, hid_dim)\n",
        "        self.h = nn.Linear(inp_dim + hid_dim, hid_dim)\n",
        "\n",
        "    def forward(self, x_t, h_prev):\n",
        "        concat = torch.cat([h_prev, x_t], dim=1)\n",
        "        f_t = torch.sigmoid(self.f(concat))\n",
        "\n",
        "        concat_new = torch.cat([f_t * h_prev, x_t], dim=1)\n",
        "        h_tilde = torch.tanh(self.h(concat_new))\n",
        "\n",
        "        h_new = (1.0 - f_t) * h_prev + f_t * h_tilde\n",
        "        return h_new\n",
        "\n",
        "# ============================================================\n",
        "# Shallow RNN classifier using custom cell\n",
        "# ============================================================\n",
        "class RNNClassifier(nn.Module):\n",
        "    \"\"\"\n",
        "    Shallow RNN:\n",
        "      - Input: (B, 1, 28, 28) image\n",
        "      - Treat as sequence of 28 rows (T=28, each of dim 28)\n",
        "      - Use custom GRU or MGU cell\n",
        "      - Final hidden state -> linear layer -> logits\n",
        "    \"\"\"\n",
        "    def __init__(self, CellType, input_dim, hidden_dim, num_classes):\n",
        "        super().__init__()\n",
        "        self.hidden_dim = hidden_dim\n",
        "        self.cell = CellType(input_dim, hidden_dim)\n",
        "        self.fc = nn.Linear(hidden_dim, num_classes)\n",
        "\n",
        "    def forward(self, x):\n",
        "        # x: (batch, 1, 28, 28) -> (batch, 28, 28)\n",
        "        x = x.squeeze(1)\n",
        "        batch_size, seq_len, feat_dim = x.shape\n",
        "        h = torch.zeros(batch_size, self.hidden_dim, device=x.device)\n",
        "\n",
        "        for t in range(seq_len):  # loop over 28 rows\n",
        "            h = self.cell(x[:, t, :], h)\n",
        "\n",
        "        out = self.fc(h)\n",
        "        return out\n",
        "\n",
        "# ============================================================\n",
        "# Data loading: MNIST as notMNIST-style sequential data\n",
        "# ============================================================\n",
        "def get_data_loaders():\n",
        "    transform = transforms.Compose([\n",
        "        transforms.ToTensor(),\n",
        "        transforms.Normalize((0.5,), (0.5,))\n",
        "    ])\n",
        "\n",
        "    full_train = torchvision.datasets.MNIST(\n",
        "        root=\"./data\", train=True, download=True, transform=transform\n",
        "    )\n",
        "    full_test = torchvision.datasets.MNIST(\n",
        "        root=\"./data\", train=False, download=True, transform=transform\n",
        "    )\n",
        "\n",
        "    # Random subsets to make training faster\n",
        "    train_indices = torch.randperm(len(full_train))[:MAX_TRAIN_SAMPLES]\n",
        "    test_indices = torch.randperm(len(full_test))[:MAX_TEST_SAMPLES]\n",
        "\n",
        "    train_ds = Subset(full_train, train_indices)\n",
        "    test_ds = Subset(full_test, test_indices)\n",
        "\n",
        "    train_loader = DataLoader(\n",
        "        train_ds, batch_size=BATCH_SIZE, shuffle=True,\n",
        "        num_workers=0, pin_memory=(DEVICE.type == \"cuda\")\n",
        "    )\n",
        "    test_loader = DataLoader(\n",
        "        test_ds, batch_size=BATCH_SIZE, shuffle=False,\n",
        "        num_workers=0, pin_memory=(DEVICE.type == \"cuda\")\n",
        "    )\n",
        "\n",
        "    print(f\"Train samples: {len(train_ds)}, Test samples: {len(test_ds)}\")\n",
        "    return train_loader, test_loader\n",
        "\n",
        "# ============================================================\n",
        "# Train + evaluate one model (one trial)\n",
        "# ============================================================\n",
        "def train_one_model(CellType, model_name, trial_id, train_loader, test_loader):\n",
        "    model = RNNClassifier(CellType, INPUT_DIM, HIDDEN_DIM, NUM_CLASSES).to(DEVICE)\n",
        "    criterion = nn.CrossEntropyLoss()\n",
        "    optimizer = optim.Adam(model.parameters(), lr=1e-3)\n",
        "\n",
        "    train_acc_hist = []\n",
        "    test_acc_hist = []\n",
        "\n",
        "    for epoch in range(EPOCHS):\n",
        "        # ---- Train ----\n",
        "        model.train()\n",
        "        correct = 0\n",
        "        total = 0\n",
        "\n",
        "        for imgs, labels in train_loader:\n",
        "            imgs = imgs.to(DEVICE)\n",
        "            labels = labels.to(DEVICE)\n",
        "\n",
        "            optimizer.zero_grad()\n",
        "            outputs = model(imgs)\n",
        "            loss = criterion(outputs, labels)\n",
        "            loss.backward()\n",
        "            optimizer.step()\n",
        "\n",
        "            _, preds = torch.max(outputs, dim=1)\n",
        "            total += labels.size(0)\n",
        "            correct += (preds == labels).sum().item()\n",
        "\n",
        "        train_acc = correct / total\n",
        "        train_acc_hist.append(train_acc)\n",
        "\n",
        "        # ---- Test ----\n",
        "        model.eval()\n",
        "        correct = 0\n",
        "        total = 0\n",
        "        with torch.no_grad():\n",
        "            for imgs, labels in test_loader:\n",
        "                imgs = imgs.to(DEVICE)\n",
        "                labels = labels.to(DEVICE)\n",
        "                outputs = model(imgs)\n",
        "                _, preds = torch.max(outputs, dim=1)\n",
        "                total += labels.size(0)\n",
        "                correct += (preds == labels).sum().item()\n",
        "\n",
        "        test_acc = correct / total\n",
        "        test_acc_hist.append(test_acc)\n",
        "\n",
        "        print(f\"{model_name} Trial {trial_id} | \"\n",
        "              f\"Epoch {epoch+1}/{EPOCHS} | \"\n",
        "              f\"Train Acc: {train_acc:.4f}, Test Acc: {test_acc:.4f}\")\n",
        "\n",
        "    # ---- Plot (save only; you can also show it if you want) ----\n",
        "    epochs_range = range(1, EPOCHS + 1)\n",
        "    plt.figure(figsize=(4.5, 3.8))\n",
        "    plt.plot(epochs_range, train_acc_hist, label=\"Train Acc\")\n",
        "    plt.plot(epochs_range, test_acc_hist, label=\"Test Acc\")\n",
        "    plt.xlabel(\"Epoch\")\n",
        "    plt.ylabel(\"Accuracy\")\n",
        "    plt.title(f\"{model_name} Trial {trial_id}\")\n",
        "    plt.legend()\n",
        "    plt.grid(True)\n",
        "    filename = f\"{model_name.lower()}_trial{trial_id}.png\"\n",
        "    plt.savefig(filename, bbox_inches=\"tight\")\n",
        "    plt.close()\n",
        "\n",
        "    return test_acc_hist[-1]  # final test accuracy of this trial\n",
        "\n",
        "# ============================================================\n",
        "# Run experiments for GRU or MGU\n",
        "# ============================================================\n",
        "def run_experiments(CellType, name, train_loader, test_loader):\n",
        "    final_accs = []\n",
        "    for t in range(TRIALS):\n",
        "        print(\"\\n======================================\")\n",
        "        print(f\"Starting {name} Trial {t}\")\n",
        "        print(\"======================================\")\n",
        "        acc = train_one_model(CellType, name, t, train_loader, test_loader)\n",
        "        final_accs.append(acc)\n",
        "\n",
        "    final_accs = np.array(final_accs)\n",
        "    mean_acc = float(final_accs.mean())\n",
        "    mean_error = 1.0 - mean_acc\n",
        "\n",
        "    print(f\"\\n{name} final test accuracies: {final_accs}\")\n",
        "    print(f\"{name} mean test accuracy: {mean_acc:.4f}\")\n",
        "    print(f\"{name} mean classification error: {mean_error:.4f}\\n\")\n",
        "\n",
        "    return final_accs, mean_error\n",
        "\n",
        "# ============================================================\n",
        "# Main\n",
        "# ============================================================\n",
        "def main():\n",
        "    train_loader, test_loader = get_data_loaders()\n",
        "\n",
        "    print(\"\\n=========================\")\n",
        "    print(\"Running GRU Experiments\")\n",
        "    print(\"=========================\")\n",
        "    gru_accs, gru_err = run_experiments(GRUCellCustom, \"GRU\",\n",
        "                                        train_loader, test_loader)\n",
        "\n",
        "    print(\"\\n=========================\")\n",
        "    print(\"Running MGU Experiments\")\n",
        "    print(\"=========================\")\n",
        "    mgu_accs, mgu_err = run_experiments(MGUCellCustom, \"MGU\",\n",
        "                                        train_loader, test_loader)\n",
        "\n",
        "    print(\"DONE. Plots saved as:\")\n",
        "    print(\"  gru_trial0.png, gru_trial1.png, gru_trial2.png\")\n",
        "    print(\"  mgu_trial0.png, mgu_trial1.png, mgu_trial2.png\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}